//
// Generated file, do not edit! Created by opp_msgtool 6.0 from job.msg.
//

#ifndef __JOB_M_H
#define __JOB_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Job;
// cplusplus {{
#include "job_base.h"  // assuming that MyClass is declared here
typedef job_base job_base; 
// }}

/**
 * Class generated from <tt>job.msg:30</tt> by opp_msgtool.
 * <pre>
 * message Job
 * {
 *     job_base *job;
 * }
 * </pre>
 */
class Job : public ::omnetpp::cMessage
{
  protected:
    job_base * job = nullptr;

  private:
    void copy(const Job& other);

  protected:
    bool operator==(const Job&) = delete;

  public:
    Job(const char *name=nullptr, short kind=0);
    Job(const Job& other);
    virtual ~Job();
    Job& operator=(const Job& other);
    virtual Job *dup() const override {return new Job(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const job_base * getJob() const;
    virtual job_base * getJobForUpdate() { return const_cast<job_base *>(const_cast<Job*>(this)->getJob());}
    virtual void setJob(job_base * job);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Job& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Job& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

inline any_ptr toAnyPtr(const job_base *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline job_base *fromAnyPtr(any_ptr ptr) { return ptr.get<job_base>(); }
template<> inline Job *fromAnyPtr(any_ptr ptr) { return check_and_cast<Job*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __JOB_M_H

